# Generated by Django 5.2.5 on 2026-05-25 08:55

import core.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pets/avatars/', validators=[django.core.validators.FileExtensionValidator({'heic', 'jpeg', 'jpg', 'png'}), core.utils.validators.max_size_image], verbose_name='Фото питомца'),
        ),
    ]
