# Generated by Django 5.2.5 on 2026-05-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_visit'),
        ('pets', '0003_alter_pet_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Аллергии')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название заболевания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание заболевания')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('controlled', 'Контролируемое'), ('remission', 'Реммися')], default='active', max_length=20, verbose_name='Статус записи')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='pets.medicalcard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакцинации')),
                ('vaccinated_at', models.DateField(verbose_name='Дата вакцинации')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('notes', models.TextField(blank=True, null=True)),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.medicalcard')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='clinics.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
