# Generated by Django 5.2.5 on 2026-05-27 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_medicalcard_chroniccondition_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chroniccondition',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='pets.medicalcard'),
        ),
    ]
