version: '3.3'
volumes:
  pg_data:
  media:
  redis_data:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    
  redis:
    image: redis:7
    container_name: petflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    container_name: petflow-back
    env_file: .env
    build: ../backend/
    command: >
      sh -c "
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  
  celery:
    container_name: petflow-celery
    build: ../backend/
    env_file: .env
    command: celery -A core worker -l info
    depends_on:
      - backend
      - redis
      - db
