# Generated by Django 5.2.5 on 2026-05-16 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_clinic_unique_clinic_per_address'),
        ('pets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_time', models.TimeField(verbose_name='Дата и время начала')),
                ('end_time', models.TimeField(verbose_name='Дата и время окончания')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Доступное время',
                'verbose_name_plural': 'Доступное время',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус записи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий пользователя')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic', verbose_name='Клиника')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.slot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'ordering': ('date', 'slot__start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('clinic', 'start_time'), name='unique_slot_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('slot', 'date', 'clinic'), name='unique_appointment_slot'),
        ),
    ]
