# Generated by Django 5.2.5 on 2026-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
    ]
