# Generated by Django 5.2.5 on 2026-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_clinic_per_address'),
        ),
    ]
