# Generated by Django 5.2.5 on 2026-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_clinic_phone'),
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='species',
            field=models.ManyToManyField(related_name='clinics', to='pets.species', verbose_name='Специализация'),
        ),
    ]
