# Generated by Django 5.2.5 on 2026-05-25 08:55

import core.utils.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinic_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/logos/', validators=[django.core.validators.FileExtensionValidator({'heic', 'jpeg', 'jpg', 'png'}), core.utils.validators.max_size_image], verbose_name='Логотип'),
        ),
    ]
