# Generated by Django 5.2.5 on 2026-05-26 13:59

import core.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_clinic_owner'),
        ('pets', '0003_alter_pet_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('visit_data', models.DateTimeField()),
                ('title', models.CharField(verbose_name='Заголовок посещения.')),
                ('complaint', models.TextField(blank=True, null=True, verbose_name='Жалобы')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='visits/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions={'pdf'}), core.utils.validators.max_size_file])),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='clinics.clinic')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pets.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
