# Generated by Django 5.2.5 on 2026-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок посещения.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_data',
            field=models.DateField(verbose_name='Дата посещения'),
        ),
    ]
