# Generated by Django 5.2.5 on 2026-05-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_alter_visit_title_alter_visit_visit_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_data',
            new_name='visit_date',
        ),
    ]
