# Generated by Django 5.2.5 on 2026-06-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_rename_visit_data_visit_visit_date'),
        ('pets', '0005_alter_chroniccondition_medical_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='pets.species', verbose_name='Специализация'),
        ),
    ]
