# Generated by Django 5.2.5 on 2026-05-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_unique_clinic_per_address'),
        ('users', '0002_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание.'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'clinic'), name='unique_user_role_clinic'),
        ),
    ]
