# Generated by Django 5.2.5 on 2026-05-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrole_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='username',
        ),
    ]
