# Generated by Django 5.2.5 on 2026-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_projectuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='projectuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
