# Generated by Django 5.2.5 on 2026-05-16 12:56

import core.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projectuser_managers_projectuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', validators=[django.core.validators.FileExtensionValidator({'jpeg', 'jpg', 'png'}), core.utils.validators.max_size_image], verbose_name='Аватар'),
        ),
    ]
