# Generated by Django 5.2.5 on 2026-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_projectuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
