# Generated by Django 5.2.5 on 2026-05-28 14:34

import core.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_rename_visit_data_visit_visit_date'),
        ('users', '0009_alter_projectuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('specialization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Специализация')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='vets/avatars', validators=[django.core.validators.FileExtensionValidator({'heic', 'jpeg', 'jpg', 'png'}), core.utils.validators.max_size_image], verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vets', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Ветеринар',
                'verbose_name_plural': 'Ветеринары',
                'ordering': ('email',),
            },
        ),
    ]
